spring.application.name=EmployeeManagementSystem

logging.level.com.cognizant.employeemanagementsystem=DEBUG

# Primary Data Source
spring.datasource.primary.jdbc-url=jdbc:h2:mem:primarydb
spring.datasource.primary.driver-class-name=org.h2.Driver
spring.datasource.primary.username=sa
spring.datasource.primary.password=password

# Secondary Data Source
spring.datasource.secondary.jdbc-url=jdbc:h2:mem:secondarydb
spring.datasource.secondary.driver-class-name=org.h2.Driver
spring.datasource.secondary.username=sa
spring.datasource.secondary.password=password

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate Batch Processing
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Hibernate Performance
spring.jpa.properties.hibernate.default_batch_fetch_size=20

# Spring Boot Server Port
server.port=8081